/* Generated By:JavaCC: Do not edit this line. MiniJavaParser.java */
    package MiniJavaParser;
    import AST.*;
    import java.util.ArrayList;
    import java.util.List;
    public class MiniJavaParser implements MiniJavaParserConstants {
//          public static void main(String args[]) {
//            MiniJavaParser parser;
//              try {
//                System.out.println("MiniJava parsing from '" + "prueba.txt" + "' file...");
//                parser = new MiniJavaParser(new java.io.FileInputStream("prueba.txt"));
//              } catch (java.io.FileNotFoundException e) {
//                System.out.println("Error: File not found.");
//                return;
//              }
//            try {
//              parser.Goal();
//              System.out.println("MiniJava program parsed successfully.");
//            } catch (ParseException e) {
//              System.out.println("Encountered errors during parse.");
//              System.out.println(e.getMessage());
//            } catch (TokenMgrError e) {
//              System.out.println("Encountered errors during Scanning.");
//              System.out.println(e.getMessage());
//            }
//        }

/************************************
 * The MiniJava Grammar Starts Here *
 ************************************/
  final public GoalAST Goal() throws ParseException {
    ArrayList<ImportDeclarationAST> implist = new ArrayList<ImportDeclarationAST>();
    ArrayList<TypeDeclarationAST> tydecls = new ArrayList<TypeDeclarationAST>();
    MainClassAST mc=null;
    ImportDeclarationAST imp=null;
    TypeDeclarationAST t=null;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IMPORT:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      imp = ImportDeclaration();
         implist.add(imp);
    }
    mc = MainClass();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CLASS:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      t = TypeDeclaration();
         tydecls.add(t);
    }
    jj_consume_token(0);
     {if (true) return  new GoalAST(implist,mc,tydecls);}
    throw new Error("Missing return statement in function");
  }

  final public ImportDeclarationAST ImportDeclaration() throws ParseException {
    SingleImportDeclarationAST sid=null;
    MultipleImportDeclarationAST mid=null;
    if (jj_2_1(2147483647)) {
      sid = SingleImportDeclaration();
     {if (true) return sid;}
    } else if (jj_2_2(2147483647)) {
      mid = MultipleImportDeclaration();
     {if (true) return mid;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public SingleImportDeclarationAST SingleImportDeclaration() throws ParseException {
    TypeNameAST tn=null;
    jj_consume_token(IMPORT);
    tn = TypeName();
    jj_consume_token(SEMICOLON);
     {if (true) return new SingleImportDeclarationAST(tn);}
    throw new Error("Missing return statement in function");
  }

  final public MultipleImportDeclarationAST MultipleImportDeclaration() throws ParseException {
    TypeNameAST tn=null;
    jj_consume_token(IMPORT);
    tn = TypeName();
    jj_consume_token(DOT);
    jj_consume_token(54);
    jj_consume_token(SEMICOLON);
     {if (true) return new MultipleImportDeclarationAST(tn);}
    throw new Error("Missing return statement in function");
  }

  final public TypeNameAST TypeName() throws ParseException {
    ArrayList<IdentifierAST> idlist = new ArrayList<IdentifierAST>();
    IdentifierAST id=null;
    id = Identifier();
    label_3:
    while (true) {
      if (jj_2_3(2)) {
        ;
      } else {
        break label_3;
      }
      jj_consume_token(DOT);
      id = Identifier();
         idlist.add(id);
    }
     {if (true) return new TypeNameAST(idlist);}
    throw new Error("Missing return statement in function");
  }

  final public MainClassAST MainClass() throws ParseException {
    IdentifierAST id1=null;
    IdentifierAST id2=null;
    PrintStatementAST pstm=null;
    jj_consume_token(CLASS);
    id1 = Identifier();
    jj_consume_token(LBRACE);
    jj_consume_token(PUBLIC);
    jj_consume_token(STATIC);
    jj_consume_token(VOID);
    jj_consume_token(MAIN);
    jj_consume_token(LPAREN);
    jj_consume_token(STRING);
    jj_consume_token(LSQPAREN);
    jj_consume_token(RSQPAREN);
    id2 = Identifier();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    pstm = PrintStatement();
    jj_consume_token(RBRACE);
    jj_consume_token(RBRACE);
     {if (true) return new MainClassAST(id1,id2,pstm);}
    throw new Error("Missing return statement in function");
  }

  final public TypeDeclarationAST TypeDeclaration() throws ParseException {
    ClassExtendsDeclarationAST cxd=null;
    ClassDeclarationAST cd=null;
    if (jj_2_4(2147483647)) {
      cxd = ClassExtendsDeclaration();
     {if (true) return cxd;}
    } else if (jj_2_5(2147483647)) {
      cd = ClassDeclaration();
     {if (true) return cd;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ClassDeclarationAST ClassDeclaration() throws ParseException {
    IdentifierAST id=null;
    VarDeclarationAST vd=null;
    ArrayList<VarDeclarationAST> vdlist = new ArrayList<VarDeclarationAST>();
    MethodDeclarationAST md=null;
    ArrayList<MethodDeclarationAST> mdlist = new ArrayList<MethodDeclarationAST>();
    jj_consume_token(CLASS);
    id = Identifier();
    jj_consume_token(LBRACE);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BOOLEAN:
      case INTEGER:
      case STRING:
      case CHAR:
      case VOID:
      case OBJECT:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_4;
      }
      vd = VarDeclaration();
             vdlist.add(vd);
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUBLIC:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_5;
      }
      md = MethodDeclaration();
             mdlist.add(md);
    }
    jj_consume_token(RBRACE);
     {if (true) return new ClassDeclarationAST(id,vdlist,mdlist);}
    throw new Error("Missing return statement in function");
  }

  final public ClassExtendsDeclarationAST ClassExtendsDeclaration() throws ParseException {
    IdentifierAST id1=null;
    IdentifierAST id2=null;
    VarDeclarationAST vd=null;
    ArrayList<VarDeclarationAST> vdlist = new ArrayList<VarDeclarationAST>();
    MethodDeclarationAST md=null;
    ArrayList<MethodDeclarationAST> mdlist = new ArrayList<MethodDeclarationAST>();
    jj_consume_token(CLASS);
    id1 = Identifier();
    jj_consume_token(EXTENDS);
    id2 = Identifier();
    jj_consume_token(LBRACE);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BOOLEAN:
      case INTEGER:
      case STRING:
      case CHAR:
      case VOID:
      case OBJECT:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_6;
      }
      vd = VarDeclaration();
         vdlist.add(vd);
    }
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUBLIC:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_7;
      }
      md = MethodDeclaration();
         mdlist.add(md);
    }
    jj_consume_token(RBRACE);
     {if (true) return new ClassExtendsDeclarationAST(id1,id2,vdlist,mdlist);}
    throw new Error("Missing return statement in function");
  }

  final public VarDeclarationAST VarDeclaration() throws ParseException {
    Type t=null;
    IdentifierAST id=null;
    t = Type();
    id = Identifier();
    jj_consume_token(SEMICOLON);
     {if (true) return new VarDeclarationAST(t,id);}
    throw new Error("Missing return statement in function");
  }

  final public MethodDeclarationAST MethodDeclaration() throws ParseException {
    Type t=null;
    IdentifierAST id=null;
    FormalParameterListAST fpl=null;
    VarDeclarationAST vd=null;
    ArrayList<VarDeclarationAST> vdlist = new ArrayList<VarDeclarationAST>();
    Statement st=null;
    ArrayList<Statement> stlist = new ArrayList<Statement>();
    Expression ex=null;
    jj_consume_token(PUBLIC);
    t = Type();
    id = Identifier();
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOLEAN:
    case INTEGER:
    case STRING:
    case CHAR:
    case VOID:
    case OBJECT:
    case IDENTIFIER:
      fpl = FormalParameterList();
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    label_8:
    while (true) {
      if (jj_2_6(2147483647)) {
        ;
      } else {
        break label_8;
      }
      vd = VarDeclaration();
         vdlist.add(vd);
    }
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
      case LBRACE:
      case NOT:
      case FALSE:
      case IF:
      case WHILE:
      case WHITCH:
      case NEW:
      case THIS:
      case TRUE:
      case PRINT:
      case INTEGER_LITERAL:
      case CHAR_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_9;
      }
      st = Statement();
         stlist.add(st);
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SEMICOLON:
          ;
          break;
        default:
          jj_la1[8] = jj_gen;
          break label_10;
        }
        jj_consume_token(SEMICOLON);
      }
    }
    jj_consume_token(RETURN);
    ex = Expression();
    jj_consume_token(SEMICOLON);
    jj_consume_token(RBRACE);
     {if (true) return new MethodDeclarationAST(t,id,fpl,vdlist,stlist,ex);}
    throw new Error("Missing return statement in function");
  }

  final public FormalParameterListAST FormalParameterList() throws ParseException {
    FormalParameterAST fp=null;
    FormalParameterRestAST fpr=null;
    ArrayList<FormalParameterRestAST> fprlist = new ArrayList<FormalParameterRestAST>();
    fp = FormalParameter();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 55:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_11;
      }
      fpr = FormalParameterRest();
     fprlist.add(fpr);
    }
 {if (true) return new FormalParameterListAST(fp,fprlist);}
    throw new Error("Missing return statement in function");
  }

  final public FormalParameterAST FormalParameter() throws ParseException {
    Type t=null;
    IdentifierAST id=null;
    t = Type();
    id = Identifier();
     {if (true) return new FormalParameterAST(t,id);}
    throw new Error("Missing return statement in function");
  }

  final public FormalParameterRestAST FormalParameterRest() throws ParseException {
    FormalParameterAST fp=null;
    jj_consume_token(55);
    fp = FormalParameter();
     {if (true) return new FormalParameterRestAST(fp);}
    throw new Error("Missing return statement in function");
  }

  final public Type Type() throws ParseException {
    SimpleType st1=null;
    TypeArrayTypeAST at1=null;
    TypeIdentifierAST id=null;
    if (jj_2_7(2147483647)) {
      st1 = SimpleType();
     {if (true) return new TypeSimpleTypeAST(st1);}
    } else if (jj_2_8(2147483647)) {
      at1 = ArrayType();
     {if (true) return at1;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        id = Identifier_t();
     {if (true) return new TypeIdentifierAST(id);}
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public SimpleType SimpleType() throws ParseException {
    CharTypeAST ct;
    BooleanTypeAST bt;
    IntegerTypeAST it;
    VoidTypeAST vt;
    ObjectTypeAST ot;
    StringTypeAST st;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CHAR:
      ct = CharType();
     {if (true) return ct;}
      break;
    case BOOLEAN:
      bt = BooleanType();
     {if (true) return bt;}
      break;
    case INTEGER:
      it = IntegerType();
     {if (true) return it;}
      break;
    case VOID:
      vt = VoidType();
     {if (true) return vt;}
      break;
    case OBJECT:
      ot = ObjectType();
     {if (true) return ot;}
      break;
    case STRING:
      st = StringType();
     {if (true) return st;}
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public TypeArrayTypeAST ArrayType() throws ParseException {
    SimpleType st=null;
    st = SimpleType();
    jj_consume_token(LSQPAREN);
    jj_consume_token(RSQPAREN);
     {if (true) return new TypeArrayTypeAST(st);}
    throw new Error("Missing return statement in function");
  }

  final public CharTypeAST CharType() throws ParseException {
    jj_consume_token(CHAR);
     {if (true) return new CharTypeAST();}
    throw new Error("Missing return statement in function");
  }

  final public BooleanTypeAST BooleanType() throws ParseException {
    jj_consume_token(BOOLEAN);
     {if (true) return new BooleanTypeAST();}
    throw new Error("Missing return statement in function");
  }

  final public ObjectTypeAST ObjectType() throws ParseException {
    jj_consume_token(OBJECT);
     {if (true) return new ObjectTypeAST();}
    throw new Error("Missing return statement in function");
  }

  final public StringTypeAST StringType() throws ParseException {
    jj_consume_token(STRING);
     {if (true) return new StringTypeAST();}
    throw new Error("Missing return statement in function");
  }

  final public IntegerTypeAST IntegerType() throws ParseException {
    jj_consume_token(INTEGER);
     {if (true) return new IntegerTypeAST();}
    throw new Error("Missing return statement in function");
  }

  final public VoidTypeAST VoidType() throws ParseException {
    jj_consume_token(VOID);
     {if (true) return new VoidTypeAST();}
    throw new Error("Missing return statement in function");
  }

  final public Statement Statement() throws ParseException {
    BlockAST a=null;
    AssignmentStatementAST b=null;
    ArrayAssignmentStatementAST c=null;
    IfElseStatementAST d=null;
    IfStatementAST e=null;
    WhileStatementAST f=null;
    SwitchStatementAST g=null;
    PrintStatementAST h=null;
    Expression i=null;
    if (jj_2_9(2147483647)) {
      a = Block();
     {if (true) return a;}
    } else if (jj_2_10(2147483647)) {
      b = AssignmentStatement();
     {if (true) return b;}
    } else if (jj_2_11(2147483647)) {
      c = ArrayAssignmentStatement();
     {if (true) return c;}
    } else if (jj_2_12(2147483647)) {
      d = IfElseStatement();
     {if (true) return d;}
    } else if (jj_2_13(2147483647)) {
      e = IfStatement();
     {if (true) return e;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WHILE:
        f = WhileStatement();
     {if (true) return f;}
        break;
      case WHITCH:
        g = SwitchStatement();
     {if (true) return g;}
        break;
      case PRINT:
        h = PrintStatement();
     {if (true) return h;}
        break;
      case LPAREN:
      case NOT:
      case FALSE:
      case NEW:
      case THIS:
      case TRUE:
      case INTEGER_LITERAL:
      case CHAR_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:
        i = Expression();
    {if (true) return i;}
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public BlockAST Block() throws ParseException {
    Statement st=null;
    ArrayList<Statement> stlist = new ArrayList<Statement>();
    jj_consume_token(LBRACE);
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
      case LBRACE:
      case NOT:
      case FALSE:
      case IF:
      case WHILE:
      case WHITCH:
      case NEW:
      case THIS:
      case TRUE:
      case PRINT:
      case INTEGER_LITERAL:
      case CHAR_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_12;
      }
      st = Statement();
         stlist.add(st);
    }
    jj_consume_token(RBRACE);
       {if (true) return new BlockAST(stlist);}
    throw new Error("Missing return statement in function");
  }

  final public AssignmentStatementAST AssignmentStatement() throws ParseException {
    IdentifierAST id=null;
    AssigmentRestAST ar=null;
    id = Identifier();
    jj_consume_token(ASSIGN);
    ar = AssigmentRest();
    jj_consume_token(SEMICOLON);
     {if (true) return new AssignmentStatementAST(id,ar);}
    throw new Error("Missing return statement in function");
  }

  final public ArrayAssignmentStatementAST ArrayAssignmentStatement() throws ParseException {
    IdentifierAST id=null;
    Expression ex=null;
    AssigmentRestAST sr=null;
    id = Identifier();
    jj_consume_token(LSQPAREN);
    ex = Expression();
    jj_consume_token(RSQPAREN);
    jj_consume_token(ASSIGN);
    sr = AssigmentRest();
    jj_consume_token(SEMICOLON);
     {if (true) return new ArrayAssignmentStatementAST(id,ex,sr);}
    throw new Error("Missing return statement in function");
  }

  final public AssigmentRestAST AssigmentRest() throws ParseException {
    Type t=null;
    Expression ex=null;
    if (jj_2_14(5)) {
      jj_consume_token(LPAREN);
      t = Type();
      jj_consume_token(RPAREN);
      jj_consume_token(56);
      jj_consume_token(LPAREN);
      jj_consume_token(RPAREN);
     {if (true) return new AssigmentRestAST(t);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
      case NOT:
      case FALSE:
      case NEW:
      case THIS:
      case TRUE:
      case INTEGER_LITERAL:
      case CHAR_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:
        ex = Expression();
     {if (true) return new AssigmentRestAST(ex);}
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public IfStatementAST IfStatement() throws ParseException {
    Expression ex=null;
    Statement st=null;
    jj_consume_token(IF);
    jj_consume_token(LPAREN);
    ex = Expression();
    jj_consume_token(RPAREN);
    st = Statement();
     {if (true) return new IfStatementAST(ex,st);}
    throw new Error("Missing return statement in function");
  }

  final public IfElseStatementAST IfElseStatement() throws ParseException {
    Expression ex=null;
    Statement stif=null;
    Statement stelse=null;
    jj_consume_token(IF);
    jj_consume_token(LPAREN);
    ex = Expression();
    jj_consume_token(RPAREN);
    stif = Statement();
    jj_consume_token(ELSE);
    stelse = Statement();
     {if (true) return new IfElseStatementAST(ex,stif,stelse);}
    throw new Error("Missing return statement in function");
  }

  final public WhileStatementAST WhileStatement() throws ParseException {
    Expression ex=null;
    Statement st=null;
    jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    ex = Expression();
    jj_consume_token(RPAREN);
    st = Statement();
     {if (true) return new WhileStatementAST(ex,st);}
    throw new Error("Missing return statement in function");
  }

  final public SwitchStatementAST SwitchStatement() throws ParseException {
    IdentifierAST id=null;
    IdentifierAST it=null;
    Statement st=null;
    ArrayList<Statement> stlist = new ArrayList<Statement>();
    jj_consume_token(WHITCH);
    jj_consume_token(LPAREN);
    id = Identifier();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    jj_consume_token(CASE);
    it = Identifier();
    jj_consume_token(57);
    jj_consume_token(LBRACE);
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
      case LBRACE:
      case NOT:
      case FALSE:
      case IF:
      case WHILE:
      case WHITCH:
      case NEW:
      case THIS:
      case TRUE:
      case PRINT:
      case INTEGER_LITERAL:
      case CHAR_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_13;
      }
      st = Statement();
             stlist.add(st);
    }
    jj_consume_token(RBRACE);
    jj_consume_token(RBRACE);
     {if (true) return new SwitchStatementAST(id,it,stlist);}
    throw new Error("Missing return statement in function");
  }

  final public PrintStatementAST PrintStatement() throws ParseException {
    Expression ex=null;
    jj_consume_token(PRINT);
    jj_consume_token(LPAREN);
    ex = Expression();
    jj_consume_token(RPAREN);
    jj_consume_token(SEMICOLON);
     {if (true) return new PrintStatementAST(ex);}
    throw new Error("Missing return statement in function");
  }

  final public Expression Expression() throws ParseException {
    AndExpressionAST a=null;
    OrExpressionAST b=null;
    EqualExpressionAST c=null;
    GreatExpressionAST d=null;
    LessExpressionAST e=null;
    PlusExpressionAST f=null;
    MinusExpressionAST g= null;
    TimesExpressionAST h=null;
    SubExpressionAST i=null;
    ArrayLookupAST j=null;
    ArrayLengthAST k=null;
    MessageSendAST l=null;
    PrimaryExpression m=null;
    if (jj_2_15(2147483647)) {
      a = AndExpression();
     {if (true) return a;}
    } else if (jj_2_16(2147483647)) {
      b = OrExpression();
     {if (true) return b;}
    } else if (jj_2_17(2147483647)) {
      c = EqualExpression();
     {if (true) return c;}
    } else if (jj_2_18(2147483647)) {
      d = GreatExpression();
     {if (true) return d;}
    } else if (jj_2_19(2147483647)) {
      e = LessExpression();
     {if (true) return e;}
    } else if (jj_2_20(2147483647)) {
      f = PlusExpression();
     {if (true) return f;}
    } else if (jj_2_21(2147483647)) {
      g = MinusExpression();
     {if (true) return g;}
    } else if (jj_2_22(2147483647)) {
      h = TimesExpression();
     {if (true) return h;}
    } else if (jj_2_23(2147483647)) {
      i = SubExpression();
     {if (true) return i;}
    } else if (jj_2_24(2147483647)) {
      j = ArrayLookup();
     {if (true) return j;}
    } else if (jj_2_25(2147483647)) {
      k = ArrayLength();
     {if (true) return k;}
    } else if (jj_2_26(2147483647)) {
      l = MessageSend();
     {if (true) return l;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
      case NOT:
      case FALSE:
      case NEW:
      case THIS:
      case TRUE:
      case INTEGER_LITERAL:
      case CHAR_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:
        m = PrimaryExpression();
     {if (true) return m;}
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public AndExpressionAST AndExpression() throws ParseException {
    PrimaryExpression pe1=null;
    PrimaryExpression pe2=null;
    pe1 = PrimaryExpression();
    jj_consume_token(58);
    pe2 = PrimaryExpression();
     {if (true) return new AndExpressionAST(pe1,pe2);}
    throw new Error("Missing return statement in function");
  }

  final public OrExpressionAST OrExpression() throws ParseException {
    PrimaryExpression pe1=null;
    PrimaryExpression pe2=null;
    pe1 = PrimaryExpression();
    jj_consume_token(59);
    pe2 = PrimaryExpression();
     {if (true) return new OrExpressionAST(pe1,pe2);}
    throw new Error("Missing return statement in function");
  }

  final public EqualExpressionAST EqualExpression() throws ParseException {
    PrimaryExpression pe1=null;
    PrimaryExpression pe2=null;
    pe1 = PrimaryExpression();
    jj_consume_token(ASSIGN);
    jj_consume_token(ASSIGN);
    pe2 = PrimaryExpression();
     {if (true) return new EqualExpressionAST(pe1,pe2);}
    throw new Error("Missing return statement in function");
  }

  final public GreatExpressionAST GreatExpression() throws ParseException {
    PrimaryExpression pe1=null;
    PrimaryExpression pe2=null;
    pe1 = PrimaryExpression();
    jj_consume_token(60);
    pe2 = PrimaryExpression();
     {if (true) return new GreatExpressionAST(pe1,pe2);}
    throw new Error("Missing return statement in function");
  }

  final public LessExpressionAST LessExpression() throws ParseException {
    PrimaryExpression pe1=null;
    PrimaryExpression pe2=null;
    pe1 = PrimaryExpression();
    jj_consume_token(LT);
    pe2 = PrimaryExpression();
     {if (true) return new LessExpressionAST(pe1,pe2);}
    throw new Error("Missing return statement in function");
  }

  final public PlusExpressionAST PlusExpression() throws ParseException {
    PrimaryExpression pe1=null;
    PrimaryExpression pe2=null;
    pe1 = PrimaryExpression();
    jj_consume_token(PLUS);
    pe2 = PrimaryExpression();
     {if (true) return new PlusExpressionAST(pe1,pe2);}
    throw new Error("Missing return statement in function");
  }

  final public MinusExpressionAST MinusExpression() throws ParseException {
    PrimaryExpression pe1=null;
    PrimaryExpression pe2=null;
    pe1 = PrimaryExpression();
    jj_consume_token(MINUS);
    pe2 = PrimaryExpression();
     {if (true) return new MinusExpressionAST(pe1,pe2);}
    throw new Error("Missing return statement in function");
  }

  final public TimesExpressionAST TimesExpression() throws ParseException {
    PrimaryExpression pe1=null;
    PrimaryExpression pe2=null;
    pe1 = PrimaryExpression();
    jj_consume_token(54);
    pe2 = PrimaryExpression();
     {if (true) return new TimesExpressionAST(pe1,pe2);}
    throw new Error("Missing return statement in function");
  }

  final public SubExpressionAST SubExpression() throws ParseException {
    PrimaryExpression pe1=null;
    PrimaryExpression pe2=null;
    pe1 = PrimaryExpression();
    jj_consume_token(61);
    pe2 = PrimaryExpression();
     {if (true) return new SubExpressionAST(pe1,pe2);}
    throw new Error("Missing return statement in function");
  }

  final public ArrayLookupAST ArrayLookup() throws ParseException {
    PrimaryExpression pe1=null;
    PrimaryExpression pe2=null;
    pe1 = PrimaryExpression();
    jj_consume_token(LSQPAREN);
    pe2 = PrimaryExpression();
    jj_consume_token(RSQPAREN);
     {if (true) return new ArrayLookupAST(pe1,pe2);}
    throw new Error("Missing return statement in function");
  }

  final public ArrayLengthAST ArrayLength() throws ParseException {
    PrimaryExpression pe1=null;
    pe1 = PrimaryExpression();
    jj_consume_token(DOT);
    jj_consume_token(LENGTH);
     {if (true) return new ArrayLengthAST(pe1);}
    throw new Error("Missing return statement in function");
  }

  final public MessageSendAST MessageSend() throws ParseException {
    PrimaryExpression pex=null;
    IdentifierAST id=null;
    ExpressionListAST exl=null;
    pex = PrimaryExpression();
    jj_consume_token(DOT);
    id = Identifier();
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN:
    case NOT:
    case FALSE:
    case NEW:
    case THIS:
    case TRUE:
    case INTEGER_LITERAL:
    case CHAR_LITERAL:
    case STRING_LITERAL:
    case IDENTIFIER:
      exl = ExpressionList();
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
     {if (true) return new MessageSendAST(pex,id,exl);}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionListAST ExpressionList() throws ParseException {
    Expression ex=null;
    ExpressionRestAST exr=null;
    ArrayList<ExpressionRestAST> exrlist = new ArrayList<ExpressionRestAST>();
    ex = Expression();
    label_14:
    while (true) {
      if (jj_2_27(2147483647)) {
        ;
      } else {
        break label_14;
      }
      exr = ExpressionRest();
         exrlist.add(exr);
    }
     {if (true) return new ExpressionListAST(ex,exrlist);}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionRestAST ExpressionRest() throws ParseException {
    Expression ex=null;
    jj_consume_token(55);
    ex = Expression();
     {if (true) return new ExpressionRestAST(ex);}
    throw new Error("Missing return statement in function");
  }

  final public PrimaryExpression PrimaryExpression() throws ParseException {
    IntegerLiteralAST a=null;
    CharConstantAST b=null;
    StringConstantAST c=null;
    TrueLiteralAST d=null;
    FalseLiteralAST e=null;
    IdentifierAST f=null;
    ThisExpressionAST g=null;
    ArrayAllocationExpressionAST h=null;
    AllocationExpressionAST i=null;
    NotExpressionAST j=null;
    BracketExpressionAST k=null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
      a = IntegerLiteral();
     {if (true) return a;}
      break;
    case CHAR_LITERAL:
      b = CharConstant();
     {if (true) return b;}
      break;
    case STRING_LITERAL:
      c = StringConstant();
     {if (true) return c;}
      break;
    case TRUE:
      d = TrueLiteral();
     {if (true) return d;}
      break;
    case FALSE:
      e = FalseLiteral();
     {if (true) return e;}
      break;
    case IDENTIFIER:
      f = Identifier();
     {if (true) return f;}
      break;
    case THIS:
      g = ThisExpression();
     {if (true) return g;}
      break;
    default:
      jj_la1[18] = jj_gen;
      if (jj_2_28(2147483647)) {
        h = ArrayAllocationExpression();
     {if (true) return h;}
      } else if (jj_2_29(2147483647)) {
        i = AllocationExpression();
     {if (true) return i;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NOT:
          j = NotExpression();
     {if (true) return j;}
          break;
        case LPAREN:
          k = BracketExpression();
     {if (true) return k;}
          break;
        default:
          jj_la1[19] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public IntegerLiteralAST IntegerLiteral() throws ParseException {
    jj_consume_token(INTEGER_LITERAL);
     {if (true) return new IntegerLiteralAST(token.image);}
    throw new Error("Missing return statement in function");
  }

  final public CharConstantAST CharConstant() throws ParseException {
    jj_consume_token(CHAR_LITERAL);
     {if (true) return new CharConstantAST();}
    throw new Error("Missing return statement in function");
  }

  final public StringConstantAST StringConstant() throws ParseException {
    jj_consume_token(STRING_LITERAL);
     {if (true) return new StringConstantAST();}
    throw new Error("Missing return statement in function");
  }

  final public TrueLiteralAST TrueLiteral() throws ParseException {
    jj_consume_token(TRUE);
     {if (true) return new TrueLiteralAST();}
    throw new Error("Missing return statement in function");
  }

  final public FalseLiteralAST FalseLiteral() throws ParseException {
    jj_consume_token(FALSE);
     {if (true) return new FalseLiteralAST();}
    throw new Error("Missing return statement in function");
  }

  final public IdentifierAST Identifier() throws ParseException {
    jj_consume_token(IDENTIFIER);
    {if (true) return new IdentifierAST(token.image);}
    throw new Error("Missing return statement in function");
  }

  final public TypeIdentifierAST Identifier_t() throws ParseException {
    jj_consume_token(IDENTIFIER);
     {if (true) return new TypeIdentifierAST(token.image);}
    throw new Error("Missing return statement in function");
  }

  final public ThisExpressionAST ThisExpression() throws ParseException {
    jj_consume_token(THIS);
     {if (true) return new ThisExpressionAST();}
    throw new Error("Missing return statement in function");
  }

  final public ArrayAllocationExpressionAST ArrayAllocationExpression() throws ParseException {
    SimpleType st=null;
    Expression ex=null;
    jj_consume_token(NEW);
    st = SimpleType();
    jj_consume_token(LSQPAREN);
    ex = Expression();
    jj_consume_token(RSQPAREN);
     {if (true) return new ArrayAllocationExpressionAST(st,ex);}
    throw new Error("Missing return statement in function");
  }

  final public AllocationExpressionAST AllocationExpression() throws ParseException {
    IdentifierAST id=null;
    BracketExpressionAST bex=null;
    jj_consume_token(NEW);
    id = Identifier();
    bex = BracketExpression();
     {if (true) return new AllocationExpressionAST(id,bex);}
    throw new Error("Missing return statement in function");
  }

  final public NotExpressionAST NotExpression() throws ParseException {
    Expression ex=null;
    jj_consume_token(NOT);
    ex = Expression();
     {if (true) return new NotExpressionAST(ex);}
    throw new Error("Missing return statement in function");
  }

  final public BracketExpressionAST BracketExpression() throws ParseException {
    Expression ex=null;
    jj_consume_token(LPAREN);
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
      case NOT:
      case FALSE:
      case NEW:
      case THIS:
      case TRUE:
      case INTEGER_LITERAL:
      case CHAR_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_15;
      }
      ex = Expression();
    }
    jj_consume_token(RPAREN);
       {if (true) return new BracketExpressionAST(ex);}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  private boolean jj_3R_24() {
    if (jj_3R_65()) return true;
    return false;
  }

  private boolean jj_3R_89() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_20()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_18() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_99() {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_19()) return true;
    if (jj_scan_token(LSQPAREN)) return true;
    if (jj_3R_20()) return true;
    if (jj_scan_token(RSQPAREN)) return true;
    return false;
  }

  private boolean jj_3R_79() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_109() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_105() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_14()) {
    jj_scanpos = xsp;
    if (jj_3R_109()) return true;
    }
    return false;
  }

  private boolean jj_3R_98() {
    if (jj_scan_token(THIS)) return true;
    return false;
  }

  private boolean jj_3_14() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_scan_token(56)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_78() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_87() {
    if (jj_3R_17()) return true;
    if (jj_scan_token(LSQPAREN)) return true;
    if (jj_3R_20()) return true;
    if (jj_scan_token(RSQPAREN)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_105()) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3R_77() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(LT)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_86() {
    if (jj_3R_17()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_105()) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3R_76() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(60)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_97() {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_18()) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3R_104() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_96() {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3R_75() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_95() {
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_85() {
    if (jj_scan_token(LBRACE)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_104()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_74() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(59)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_94() {
    if (jj_scan_token(CHAR_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_scan_token(IF)) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_3R_92()) return true;
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_3R_91()) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_20()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_21()) return true;
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_93() {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_73() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(58)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_3R_90()) return true;
    return false;
  }

  private boolean jj_3_29() {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_3R_17()) return true;
    if (jj_scan_token(LSQPAREN)) return true;
    if (jj_3R_20()) return true;
    if (jj_scan_token(RSQPAREN)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3_26() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(DOT)) return true;
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_3R_102()) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_3R_89()) return true;
    return false;
  }

  private boolean jj_3_28() {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_3R_17()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_3R_101()) return true;
    return false;
  }

  private boolean jj_3_25() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(LENGTH)) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_3R_88()) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_scan_token(LBRACE)) return true;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_3R_100()) return true;
    return false;
  }

  private boolean jj_3_24() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(LSQPAREN)) return true;
    if (jj_3R_22()) return true;
    if (jj_scan_token(RSQPAREN)) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_3R_87()) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_3R_84()) return true;
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_3R_99()) return true;
    return false;
  }

  private boolean jj_3_23() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(61)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_3R_86()) return true;
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_3R_83()) return true;
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_3R_98()) return true;
    return false;
  }

  private boolean jj_3_22() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_21() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_3R_85()) return true;
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3_21() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_3R_97()) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_3R_81()) return true;
    return false;
  }

  private boolean jj_3_20() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_3R_96()) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_3R_95()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_3R_80()) return true;
    return false;
  }

  private boolean jj_3_19() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(LT)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_3R_94()) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_3R_79()) return true;
    return false;
  }

  private boolean jj_3_18() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(60)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_22() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) {
    jj_scanpos = xsp;
    if (jj_3R_63()) {
    jj_scanpos = xsp;
    if (jj_3R_64()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_3R_93()) return true;
    return false;
  }

  private boolean jj_3R_70() {
    if (jj_scan_token(VOID)) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_3R_78()) return true;
    return false;
  }

  private boolean jj_3_17() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3_16() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(59)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_69() {
    if (jj_scan_token(INTEGER)) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_3R_76()) return true;
    return false;
  }

  private boolean jj_3_15() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(58)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_3R_75()) return true;
    return false;
  }

  private boolean jj_3R_72() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(CLASS)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(LBRACE)) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_3R_74()) return true;
    return false;
  }

  private boolean jj_3R_111() {
    if (jj_scan_token(55)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3_27() {
    if (jj_scan_token(55)) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(CLASS)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(EXTENDS)) return true;
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_3R_73()) return true;
    return false;
  }

  private boolean jj_3R_71() {
    if (jj_scan_token(OBJECT)) return true;
    return false;
  }

  private boolean jj_3R_110() {
    if (jj_3R_111()) return true;
    return false;
  }

  private boolean jj_3R_68() {
    if (jj_scan_token(BOOLEAN)) return true;
    return false;
  }

  private boolean jj_3R_108() {
    if (jj_3R_20()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_110()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_67() {
    if (jj_scan_token(CHAR)) return true;
    return false;
  }

  private boolean jj_3R_103() {
    if (jj_3R_108()) return true;
    return false;
  }

  private boolean jj_3R_92() {
    if (jj_scan_token(PRINT)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_20()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3R_84() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_103()) jj_scanpos = xsp;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_65() {
    if (jj_3R_19()) return true;
    if (jj_scan_token(LSQPAREN)) return true;
    if (jj_scan_token(RSQPAREN)) return true;
    return false;
  }

  private boolean jj_3R_106() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_3R_72()) return true;
    return false;
  }

  private boolean jj_3R_91() {
    if (jj_scan_token(WHITCH)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_scan_token(LBRACE)) return true;
    if (jj_scan_token(CASE)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(57)) return true;
    if (jj_scan_token(LBRACE)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_106()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RBRACE)) return true;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_83() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(LENGTH)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(DOT)) return true;
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_3R_71()) return true;
    return false;
  }

  private boolean jj_3R_107() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_3R_17()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_3()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_3R_70()) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_3R_69()) return true;
    return false;
  }

  private boolean jj_3R_82() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(LSQPAREN)) return true;
    if (jj_3R_22()) return true;
    if (jj_scan_token(RSQPAREN)) return true;
    return false;
  }

  private boolean jj_3R_102() {
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_107()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_3R_68()) return true;
    return false;
  }

  private boolean jj_3R_19() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_3R_67()) return true;
    return false;
  }

  private boolean jj_3R_90() {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_20()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_101() {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_81() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(61)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_19()) return true;
    if (jj_scan_token(LSQPAREN)) return true;
    if (jj_scan_token(RSQPAREN)) return true;
    return false;
  }

  private boolean jj_3R_88() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_20()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_21()) return true;
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(IMPORT)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(54)) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_100() {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_17()) return true;
    if (jj_3R_102()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(IMPORT)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_3R_66()) return true;
    return false;
  }

  private boolean jj_3R_80() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(54)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public MiniJavaParserTokenManager token_source;
  JavaCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[21];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x1000000,0x800000,0x0,0x800000,0x0,0x800000,0xf0402200,0x8000,0x0,0x0,0x800000,0xd0400200,0xf0402200,0x10400200,0xf0402200,0x10400200,0x10400200,0x10000000,0x400200,0x10400200,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x2000,0x0,0x8d081,0x10,0x8d081,0x10,0x8d081,0xf0708,0x0,0x800000,0x80000,0xd081,0xf0708,0xf0708,0xf0308,0xf0708,0xf0308,0xf0308,0xf0300,0x0,0xf0308,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[29];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniJavaParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniJavaParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MiniJavaParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniJavaParser(java.io.Reader stream) {
    jj_input_stream = new JavaCharStream(stream, 1, 1);
    token_source = new MiniJavaParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniJavaParser(MiniJavaParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniJavaParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 21; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[62];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 21; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 62; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 29; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

    }
